### ISSUE TITLE
Non functional RTC

### ISSUE THREAD

**Issue by germanh1982** [linshuqin329/UPS-18650#12]
Hi @linshuqin329 

I just bought two of these boards (v1.1) from a reseller located in Argentina.

There's a problem with the RTC subsystem. The PCB is designed for a DS1307 but the boards I got have a DS1302 installed in their place. The pinouts on both chips is different so obviously the I2C scan on bus 1 of the RPi doesn't show anything on address 0x68.

Just wanted to let you know in case you had anything to do with the manufacturing/supply chain of this project.
BR, German

**Comment by linshuqin329** [comment]
@germanh1982 I think you bought a fake UPS-18650.I have stopped the production of UPS-18650 two years ago, and the products available on the market are basically fake. You can send me the photo of the UPS-18650 you purchased for confirmation.If it is confirmed that it is a fake, I suggest you to complain to the shop where you bought it and apply for a refund, asking him to stop selling fake products. 

The other new news is that a new UPS-18650 PRO version is being designed

**Comment by germanh1982** [comment]
Thank you for your quick answer.

Here are photos of both sides of the board. They came in a ESD bag without anything else. The boards are labelled "UPS-18650 V1.1 Designed by XiaoJ and Made in China" (it may not be clear in the photos because the black solder mask makes it very difficult to read). The only way I could match the board with this project was by googling "Xiaoj rpi 18650".

https://drive.google.com/file/d/1XEH_UVTsjj0xANh2aK6nObfgcnyXKnsA/view?usp=drive_link
https://drive.google.com/file/d/1LzNTHcImEFy_ixdnHQce9BSByry1M6Ov/view?usp=drive_link

I took out the DS1302 and battery on that board, to test it with the correct parts.

If they're fake (which it seems they are) it all makes sense. Sorry for the inconvenience, and I'll be looking forward for the new version!
Regards, German

**Comment by linshuqin329** [comment]
@germanh1982 I'm sure your ups-18650 is a fake

**Comment by germanh1982** [comment]
Thanks, I'll file a complaint to the seller.
BR, German
