### ISSUE TITLE
Charging battery to 80%

### ISSUE THREAD

**Issue by Keralots** [linshuqin329/UPS-18650#6]
Hello.

Is it possible to modify/update firmware in your UPS to charge battery to for example maximum 80%?
UPS is connected all the time and I'm thinking if charging batteries to 80% will increase it's lifespan.

It would be also great to start charging process only if battery level will drop below specified level. (e.g. 70-80%)

Regards,

**Comment by linshuqin329** [comment]
sorry，in this UPS version ，charge battery is controlled by the Lithium-Ion Linear Battery Charge Controller, so can’t modify it. the  Charger Controlle will monitor the voltage of the battery and decide when to recharge the battery. in next version, i will add a MCU to do more operation. Thanks for your advice

**Comment by Keralots** [comment]
Thanks for information. Looking forward for next version! I will definetly buy it.
It would be also great if you could open source UPS firmware so less experience guys like me can start modifying it.

Keep up great work. Quality of your product is great.
